### PR TITLE
Add heroku

### PR DESCRIPTION
**Pull request by ChappIO**

### CODE REVIEW

**Comment by ChappIO** [comment]
Fixes #3

**Comment by Badbond** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/GitBreakers/procrastimaster/pull-request/18/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=GitBreakers/procrastimaster)

**Comment by LucaScorpion** [comment]
:+1: Code

[Approved with PullApprove](https://pullapprove.com/GitBreakers/procrastimaster/pull-request/18/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=GitBreakers/procrastimaster)

**Comment by ChappIO** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/GitBreakers/procrastimaster/pull-request/18/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=GitBreakers/procrastimaster)

**Pull request merged**
