### PR TITLE
Set up client project structure

### PR DESCRIPTION
**Pull request by ChappIO**

### CODE REVIEW

**Comment by ChappIO** [comment]
:+1:

**Comment by ChappIO** [comment]
:+1:

**Comment by Badbond** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/GitBreakers/procrastimaster/pull-request/8/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=GitBreakers/procrastimaster)

**Comment by ChappIO** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/GitBreakers/procrastimaster/pull-request/8/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=GitBreakers/procrastimaster)

**Comment by sanvisser** [comment]
👍  Code approved!

**Pull request merged**
